//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Catalogue
    {
        public int ItemNo { get; set; }
        public string Category { get; set; }
        public string Description { get; set; }
        public int ReorderLevel { get; set; }
        public int ReorderQty { get; set; }
        public string UnitMeasure { get; set; }
        public string Location { get; set; }
        public int SupPrice1 { get; set; }
        public int SupPrice2 { get; set; }
        public int SupPrice3 { get; set; }
    
        public virtual StockAdjustment StockAdjustment { get; set; }
    }
}
