//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class DisbursementDetail
    {
        public int DisbursementDetNo { get; set; }
        public int QtyRequested { get; set; }
        public int QtyReceived { get; set; }
        public string Reason { get; set; }
        public string Status { get; set; }
        public string ItemNo { get; set; }
        public int DisbursementNo { get; set; }
    
        public virtual ListOfUndisburse ListOfUndisburse { get; set; }
        public virtual Catalogue Catalogue { get; set; }
        public virtual Disbursement Disbursement { get; set; }
    }
}
