//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory
    {
        public int StockId { get; set; }
        public string ItemNo { get; set; }
        public int Balance { get; set; }
        public int Qty { get; set; }
        public System.DateTime Date { get; set; }
        public int AmountChange { get; set; }
        public int EmployeeNo { get; set; }
        public string SupplierCode { get; set; }
        public string Details { get; set; }
    
        public virtual Catalogue Catalogue { get; set; }
    }
}
