//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListOfUndisburse
    {
        public int ListOfUndisburseId { get; set; }
        public int DisbursementDetNo { get; set; }
    
        public virtual DisbursementDetail DisbursementDetail { get; set; }
    }
}
