//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class RetrievalDetail
    {
        public int RetrievalDetId { get; set; }
        public string ItemNo { get; set; }
        public int RetrievedQty { get; set; }
        public int RequiredQty { get; set; }
        public int RetrievalId { get; set; }
    
        public virtual Catalogue Catalogue { get; set; }
        public virtual Retrieval Retrieval { get; set; }
    }
}
