//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockAdjustment
    {
        public int StockAdjustmentId { get; set; }
        public System.DateTime DateRequest { get; set; }
        public string ItemNo { get; set; }
        public int Discrepancy { get; set; }
        public string Notes { get; set; }
        public string Status { get; set; }
        public System.DateTime DateOfDecision { get; set; }
        public System.DateTime DateOfRequest { get; set; }
        public long ApproveBy { get; set; }
        public int SubmittedBy { get; set; }
    
        public virtual Catalogue Catalogue { get; set; }
    }
}
