//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplier
    {
        public int SupplierCode { get; set; }
        public string SupplierName { get; set; }
        public string ContactName { get; set; }
        public int PhoneNo { get; set; }
        public int FaxNo { get; set; }
        public string SupplierAddress { get; set; }
        public int GstNo { get; set; }
        public System.DateTime Year { get; set; }
    
        public virtual Purchase Purchase { get; set; }
    }
}
